name: Issues by Team Members Only
on:
  issues:
    types: [opened]

jobs:
  check-team:
    runs-on: ubuntu-latest
    steps:
      #- uses: jricher/workflow-integration@v0.0.3
      - uses: hmarr/debug-action@v1.0.0
